[package]
name = "steel-loader"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
steel-api.workspace = true
abi_stable.workspace = true
libloading.workspace = true

[lints]
# workspace = true
